apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-kwin-setting
spec:
  forms:
    - group: basics
      label: 全局设置
      formSchema:
        - $formkit: text
          name: site_icp
          label: 站点备案信息
          value: ""

    - group: sidebar
      label: 侧栏
      formSchema:
        - $formkit: repeater
          name: socials
          label: 社交链接
          value:
            - icon: fab fa-github
              url: https://github.com/quinnInChina
          max: 5
          children:
            - $formkit: text
              name: icon
              label: 图标
              value: ""
              required: true
            - $formkit: text
              name: url
              label: 链接
              value: ""
              required: true